# Generated by Django 2.0.2 on 2018-07-06 12:34

import json
from django.db import migrations


def insert_from_json(apps, schema_editor):
    Departure = apps.get_model('departures', 'Departure')

    f = open('departures.json')
    data_list = json.loads(f.read())

    departure_obj_list = list()

    for _data in data_list:
        departure_obj = Departure(
            name=_data.get('name'),
            start_date=_data.get('start_date'),
            finish_date=_data.get('finish_date'),
            category=_data.get('category')
        )
        departure_obj_list.append(departure_obj)

    Departure.objects.bulk_create(departure_obj_list)


class Migration(migrations.Migration):

    dependencies = [
        ('departures', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_from_json),
    ]
